# HAM10000 Metadata Filtering

Filtrimi i metadata folder dhe mbajtja vetem e imazheve qe ekzistojne ne folderat e ri per klasifikim binar (mel dhe nv)

<h4> Dataset Paths <h4>

In [6]:
import os
import pandas as pd

BASE_DIR = os.getcwd()

METADATA_PATH = os.path.join(
    BASE_DIR,
    "HAM10000_metadata.csv"
)

MEL_DIR = os.path.join(
    BASE_DIR,
    "mel"
)

NV_DIR = os.path.join(
    BASE_DIR,
    "nv"
)

#print("Base directory:", BASE_DIR)

<h4> Funksioni per leximin e imazheve <h4>

In [7]:
def get_image_ids(folder_path):
    ids = set()

    for fname in os.listdir(folder_path):
        if fname.lower().endswith(".jpg"):
            ids.add(os.path.splitext(fname)[0])

    return ids

<h4> Leximi i metadata <h4>

In [8]:
df = pd.read_csv(METADATA_PATH)

print("Columns:")
print(df.columns.tolist())

print("\nTotal rows:")
print(len(df))

df.head()

Columns:
['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization']

Total rows:
10015

     lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

<h4> Gjetja automatike e kolones ID <h4>

In [10]:
possible_cols = [
    "image_id",
    "image",
    "lesion_id"
]

id_col = None

for col in possible_cols:
    if col in df.columns:
        id_col = col
        break

if id_col is None:
    raise ValueError(
        "Could not find an image identifier column in metadata."
    )

#print("Using column:", id_col)

<h4> Leximi i fotove nga folderat <h4>

In [11]:
mel_ids = get_image_ids(MEL_DIR)
nv_ids = get_image_ids(NV_DIR)

valid_ids = mel_ids.union(nv_ids)

print("Mel images:", len(mel_ids))
print("NV images:", len(nv_ids))
print("Total images:", len(valid_ids))

Mel images: 1113
NV images: 1113
Total images: 2226

<h4> Filtrimi i Metadata <h4>

In [12]:
filtered_df = df[
    df[id_col].isin(valid_ids)
].reset_index(drop=True)

print(
    f"Rows kept: {len(filtered_df)} / {len(df)}"
)

filtered_df.head()

Rows kept: 2226 / 10015

     lesion_id      image_id   dx dx_type   age     sex     localization
0  HAM_0000871  ISIC_0025964  mel   histo  40.0  female            chest
1  HAM_0000871  ISIC_0030623  mel   histo  40.0  female            chest
2  HAM_0000040  ISIC_0027190  mel   histo  80.0    male  upper extremity
3  HAM_0005678  ISIC_0031023  mel   histo  60.0    male            chest
4  HAM_0005678  ISIC_0028086  mel   histo  60.0    male            chest

<h4> Ruajtja e CSV-se se filtruar <h4>

In [15]:
output_path = os.path.join(
    BASE_DIR,
    "HAM10000_metadata_filtered.csv"
)

filtered_df.to_csv(
    output_path,
    index=False
)

#print("Saved to:")
#print(output_path)

<h4> Verifikimi <h4>

In [16]:
saved_df = pd.read_csv(output_path)

print("Saved rows:", len(saved_df))
saved_df.head()

Saved rows: 2226

     lesion_id      image_id   dx dx_type   age     sex     localization
0  HAM_0000871  ISIC_0025964  mel   histo  40.0  female            chest
1  HAM_0000871  ISIC_0030623  mel   histo  40.0  female            chest
2  HAM_0000040  ISIC_0027190  mel   histo  80.0    male  upper extremity
3  HAM_0005678  ISIC_0031023  mel   histo  60.0    male            chest
4  HAM_0005678  ISIC_0028086  mel   histo  60.0    male            chest